version: '3'
services:
  backend:
    image: zenika/marcel-backend:dev
    build: ../backend
    ports:
     - 8090:8090
    volumes:
     - ./data:/backend/data
     - ./plugins:/backend/plugins
     - ./medias:/backend/medias
     - ./logs:/backend/logs

  back-office:
    image: zenika/marcel-backoffice:dev
    build: ../back-office
    ports:
     - 81:80
    volumes:
     - ./back-office:/usr/share/nginx/html/conf

  front-end:
    image: zenika/marcel-frontend:dev
    build: ../frontend
    ports:
     - "80:80"
    volumes:
     - ./front-end:/usr/share/nginx/html/conf
     - ./release:/usr/share/nginx/html/release
